version: '3.1'

volumes:
  boilerplate-postgres:

networks:
  base:

services:
  api:
    container_name: boilerplate-api
    image: node:14
    working_dir: /usr/src/app
    restart: always
    env_file: .env
    command: bash -c "npm i && npm run debug"
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./.:/usr/src/app/.
    ports:
      - "3000:3000"
      - "9222:9222"
    networks:
      - base
  postgres:
    image: postgres:alpine
    container_name: boilerplate-postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - boilerplate-postgres:/var/lib/postgresql/data
    networks:
      - base
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: boilerplate

  pgadmin:
    image: dpage/pgadmin4
    container_name: boilerplate-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@docker.com'
      PGADMIN_DEFAULT_PASSWORD: 'docker'
    ports:
      - 8080:80
    depends_on:
      - postgres
    networks:
      - base
