version: '3.1'

volumes:
  boilerplate-postgres:
  boilerplate-mongo:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:

networks:
  base:

services:
  api:
    container_name: boilerplate-api
    image: node:16.14.2
    working_dir: /usr/src/app
    restart: always
    env_file: .env
    command: bash -c "npm i && npm run dev"
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./.:/usr/src/app/
    ports:
      - "3000:3000"
      - "9222:9222"
    networks:
      - base

  postgres:
    image: postgres:alpine
    container_name: boilerplate-postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - boilerplate-postgres:/var/lib/postgresql/data
      - ./init-sonar-database.sql:/docker-entrypoint-initdb.d/init-sonar-database.sql
    networks:
      - base
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate

  pgadmin:
    image: dpage/pgadmin4
    container_name: boilerplate-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@docker.com'
      PGADMIN_DEFAULT_PASSWORD: 'docker'
    ports:
      - 8000:80
    depends_on:
      - postgres
    networks:
      - base

  mongo:
    container_name: boilerplate-mongodb
    image: mongo
    ports:
      - '27017:27017'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: docker
      ME_CONFIG_MONGODB_ADMINPASSWORD: docker
    volumes:
      - boilerplate-mongo:/var/opt/mongo/data
    networks:
      - base

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: docker
      ME_CONFIG_BASICAUTH_PASSWORD: docker
    depends_on:
      - mongo
    networks:
      - base

  sonar:
    container_name: boilerplate-sonar
    image: sonarqube:latest
    depends_on:
      - postgres
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - base
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
